Add testcafe config
DevExpress/eslint-config-devextreme pull request #2
Opened 2020-06-01 16:31 UTC by churkin

2020-06-01 16:35 UTC, churkin commented on README.md
> +- **The additional global variables**
@RomanTsukanov check this new section's titile pls.

2020-06-02 07:21 UTC, RomanTsukanov requested changes

2020-06-02 07:21 UTC, RomanTsukanov commented on README.md
> +- **The additional global variables**
```suggestion
- **Additional global variables**
```

2020-06-02 07:36 UTC, RomanTsukanov approved these changes

2020-06-02 08:17 UTC, NickMitrokhin approved these changes

2020-06-02 08:26 UTC, merged