Update testcafe config
DevExpress/eslint-config-devextreme pull request #4
Opened 2020-06-15 16:45 UTC by churkin

2020-06-15 17:07 UTC, nightskylark approved these changes

2020-06-16 07:59 UTC, RomanTsukanov requested changes

2020-06-16 07:59 UTC, RomanTsukanov commented on README.md
> +  - Tests can use any type of dependencies.
```suggestion
  - Allow using any types of dependencies:
```

2020-06-16 07:59 UTC, RomanTsukanov commented on README.md
> +  - We should test event handlers that use modified params to work.
```suggestion
  - Allow modifying parameters in event handlers to test these use cases:
```

2020-06-16 07:59 UTC, RomanTsukanov commented on README.md
> +  - It's a common case for the TestCafe tests that does not affect the performance.
```suggestion
- Allow `await` inside of loops. This is a common case for TestCafe tests.
```

2020-06-16 08:08 UTC, IlyaKhD approved these changes

2020-06-16 09:26 UTC, RomanTsukanov approved these changes

2020-06-16 09:45 UTC, merged